// Generated by gencpp from file fetch_control/CanSeeCube.msg
// DO NOT EDIT!


#ifndef FETCH_CONTROL_MESSAGE_CANSEECUBE_H
#define FETCH_CONTROL_MESSAGE_CANSEECUBE_H

#include <ros/service_traits.h>


#include <fetch_control/CanSeeCubeRequest.h>
#include <fetch_control/CanSeeCubeResponse.h>


namespace fetch_control
{

struct CanSeeCube
{

typedef CanSeeCubeRequest Request;
typedef CanSeeCubeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CanSeeCube
} // namespace fetch_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_control::CanSeeCube > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::fetch_control::CanSeeCube&) { return value(); }
};

template<>
struct DataType< ::fetch_control::CanSeeCube > {
  static const char* value()
  {
    return "fetch_control/CanSeeCube";
  }

  static const char* value(const ::fetch_control::CanSeeCube&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_control::CanSeeCubeRequest> should match 
// service_traits::MD5Sum< ::fetch_control::CanSeeCube > 
template<>
struct MD5Sum< ::fetch_control::CanSeeCubeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_control::CanSeeCube >::value();
  }
  static const char* value(const ::fetch_control::CanSeeCubeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_control::CanSeeCubeRequest> should match 
// service_traits::DataType< ::fetch_control::CanSeeCube > 
template<>
struct DataType< ::fetch_control::CanSeeCubeRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_control::CanSeeCube >::value();
  }
  static const char* value(const ::fetch_control::CanSeeCubeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_control::CanSeeCubeResponse> should match 
// service_traits::MD5Sum< ::fetch_control::CanSeeCube > 
template<>
struct MD5Sum< ::fetch_control::CanSeeCubeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_control::CanSeeCube >::value();
  }
  static const char* value(const ::fetch_control::CanSeeCubeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_control::CanSeeCubeResponse> should match 
// service_traits::DataType< ::fetch_control::CanSeeCube > 
template<>
struct DataType< ::fetch_control::CanSeeCubeResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_control::CanSeeCube >::value();
  }
  static const char* value(const ::fetch_control::CanSeeCubeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_CONTROL_MESSAGE_CANSEECUBE_H
