// Generated by gencpp from file graspit_interface/CheckGraspReachabilityResult.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_CHECKGRASPREACHABILITYRESULT_H
#define GRASPIT_INTERFACE_MESSAGE_CHECKGRASPREACHABILITYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct CheckGraspReachabilityResult_
{
  typedef CheckGraspReachabilityResult_<ContainerAllocator> Type;

  CheckGraspReachabilityResult_()
    : isPossible(false)
    , grasp_id(0)  {
    }
  CheckGraspReachabilityResult_(const ContainerAllocator& _alloc)
    : isPossible(false)
    , grasp_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _isPossible_type;
  _isPossible_type isPossible;

   typedef int32_t _grasp_id_type;
  _grasp_id_type grasp_id;




  typedef boost::shared_ptr< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> const> ConstPtr;

}; // struct CheckGraspReachabilityResult_

typedef ::graspit_interface::CheckGraspReachabilityResult_<std::allocator<void> > CheckGraspReachabilityResult;

typedef boost::shared_ptr< ::graspit_interface::CheckGraspReachabilityResult > CheckGraspReachabilityResultPtr;
typedef boost::shared_ptr< ::graspit_interface::CheckGraspReachabilityResult const> CheckGraspReachabilityResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'graspit_interface': ['/home/masatoshichang/robotics/fetch_ws/src/graspit_interface/msg', '/home/masatoshichang/robotics/fetch_ws/devel/share/graspit_interface/msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30778d17abcbeb0ad51e654b670ff523";
  }

  static const char* value(const ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30778d17abcbeb0aULL;
  static const uint64_t static_value2 = 0xd51e654b670ff523ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/CheckGraspReachabilityResult";
  }

  static const char* value(const ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool isPossible\n\
int32 grasp_id\n\
";
  }

  static const char* value(const ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isPossible);
      stream.next(m.grasp_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckGraspReachabilityResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::CheckGraspReachabilityResult_<ContainerAllocator>& v)
  {
    s << indent << "isPossible: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isPossible);
    s << indent << "grasp_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grasp_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_CHECKGRASPREACHABILITYRESULT_H
