// Generated by gencpp from file graspit_interface/PlanGraspsFeedback.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_PLANGRASPSFEEDBACK_H
#define GRASPIT_INTERFACE_MESSAGE_PLANGRASPSFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct PlanGraspsFeedback_
{
  typedef PlanGraspsFeedback_<ContainerAllocator> Type;

  PlanGraspsFeedback_()
    : current_step(0)
    , current_num_grasps(0)  {
    }
  PlanGraspsFeedback_(const ContainerAllocator& _alloc)
    : current_step(0)
    , current_num_grasps(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_step_type;
  _current_step_type current_step;

   typedef int32_t _current_num_grasps_type;
  _current_num_grasps_type current_num_grasps;




  typedef boost::shared_ptr< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PlanGraspsFeedback_

typedef ::graspit_interface::PlanGraspsFeedback_<std::allocator<void> > PlanGraspsFeedback;

typedef boost::shared_ptr< ::graspit_interface::PlanGraspsFeedback > PlanGraspsFeedbackPtr;
typedef boost::shared_ptr< ::graspit_interface::PlanGraspsFeedback const> PlanGraspsFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'graspit_interface': ['/home/masatoshichang/robotics/fetch_ws/src/graspit_interface/msg', '/home/masatoshichang/robotics/fetch_ws/devel/share/graspit_interface/msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04ac0f69e255f7fd23b3c7fcb11a47bf";
  }

  static const char* value(const ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04ac0f69e255f7fdULL;
  static const uint64_t static_value2 = 0x23b3c7fcb11a47bfULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/PlanGraspsFeedback";
  }

  static const char* value(const ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback \n\
int32 current_step\n\
int32 current_num_grasps\n\
\n\
";
  }

  static const char* value(const ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_step);
      stream.next(m.current_num_grasps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanGraspsFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::PlanGraspsFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_step: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_step);
    s << indent << "current_num_grasps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_num_grasps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_PLANGRASPSFEEDBACK_H
