walls: 
  - name: "table"
    x_thickness: 0.75
    y_thickness: 0.75 
    z_thickness: 0.05
    qx: 0 
    qy: 0
    qz: 0
    qw: 1
    x: 0.5
    y: 0.3
    z: -0.0255
    frame_id: world
  - name: "wall"
    x_thickness: 0.75
    y_thickness: 0.75 
    z_thickness: 0.05
    qx: 0.70711 
    qy: 0
    qz: 0
    qw: 0.70711
    x: 1
    y: 1
    z: -0.0255
    frame_id: world

