walls: 
  - name: "table"
    x_thickness: 0.75
    y_thickness: 1.5
    z_thickness: 0.05
    qx: 0 
    qy: 0
    qz: 0
    qw: 1
    x: 0.25
    y: -0.5
    z: 0.0
    frame_id: world
  - name: "stand"
    x_thickness: 0.10
    y_thickness: 0.2
    z_thickness: 0.04
    qx: 0 
    qy: 0
    qz: 0
    qw: 1
    x: 0.15
    y: -0.5
    z: 0.05
    frame_id: world
  - name: "right_wall"
    x_thickness: 0.75
    y_thickness: 0.75 
    z_thickness: 0.05
    qx: 0.70711 
    qy: 0
    qz: 0
    qw: 0.70711
    x: 0.3
    y: -1.2
    z: -0.0255
    frame_id: world
  - name: "back_wall"
    x_thickness: 0.75
    y_thickness: 1.5
    z_thickness: 0.05
    qx: 0
    qy: 0.70711 
    qz: 0
    qw: 0.70711
    x: -0.75
    y: -0.75
    z: -0.0255
    frame_id: world

