; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude AfterGraspingFeedback.msg.html

(cl:defclass <AfterGraspingFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass AfterGraspingFeedback (<AfterGraspingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AfterGraspingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AfterGraspingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<AfterGraspingFeedback> is deprecated: use graspit_msgs-msg:AfterGraspingFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AfterGraspingFeedback>) ostream)
  "Serializes a message object of type '<AfterGraspingFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AfterGraspingFeedback>) istream)
  "Deserializes a message object of type '<AfterGraspingFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AfterGraspingFeedback>)))
  "Returns string type for a message object of type '<AfterGraspingFeedback>"
  "graspit_msgs/AfterGraspingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AfterGraspingFeedback)))
  "Returns string type for a message object of type 'AfterGraspingFeedback"
  "graspit_msgs/AfterGraspingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AfterGraspingFeedback>)))
  "Returns md5sum for a message object of type '<AfterGraspingFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AfterGraspingFeedback)))
  "Returns md5sum for a message object of type 'AfterGraspingFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AfterGraspingFeedback>)))
  "Returns full string definition for message of type '<AfterGraspingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AfterGraspingFeedback)))
  "Returns full string definition for message of type 'AfterGraspingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AfterGraspingFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AfterGraspingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AfterGraspingFeedback
))
