; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude AfterGraspingGoal.msg.html

(cl:defclass <AfterGraspingGoal> (roslisp-msg-protocol:ros-message)
  ((action
    :reader action
    :initarg :action
    :type cl:string
    :initform ""))
)

(cl:defclass AfterGraspingGoal (<AfterGraspingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AfterGraspingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AfterGraspingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<AfterGraspingGoal> is deprecated: use graspit_msgs-msg:AfterGraspingGoal instead.")))

(cl:ensure-generic-function 'action-val :lambda-list '(m))
(cl:defmethod action-val ((m <AfterGraspingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:action-val is deprecated.  Use graspit_msgs-msg:action instead.")
  (action m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AfterGraspingGoal>) ostream)
  "Serializes a message object of type '<AfterGraspingGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'action))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'action))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AfterGraspingGoal>) istream)
  "Deserializes a message object of type '<AfterGraspingGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'action) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'action) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AfterGraspingGoal>)))
  "Returns string type for a message object of type '<AfterGraspingGoal>"
  "graspit_msgs/AfterGraspingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AfterGraspingGoal)))
  "Returns string type for a message object of type 'AfterGraspingGoal"
  "graspit_msgs/AfterGraspingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AfterGraspingGoal>)))
  "Returns md5sum for a message object of type '<AfterGraspingGoal>"
  "7757aad79fa343e61bc69ed7f1b7666d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AfterGraspingGoal)))
  "Returns md5sum for a message object of type 'AfterGraspingGoal"
  "7757aad79fa343e61bc69ed7f1b7666d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AfterGraspingGoal>)))
  "Returns full string definition for message of type '<AfterGraspingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string action~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AfterGraspingGoal)))
  "Returns full string definition for message of type 'AfterGraspingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string action~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AfterGraspingGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'action))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AfterGraspingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AfterGraspingGoal
    (cl:cons ':action (action msg))
))
