; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude CheckGraspReachabilityGoal.msg.html

(cl:defclass <CheckGraspReachabilityGoal> (roslisp-msg-protocol:ros-message)
  ((grasp
    :reader grasp
    :initarg :grasp
    :type graspit_msgs-msg:Grasp
    :initform (cl:make-instance 'graspit_msgs-msg:Grasp)))
)

(cl:defclass CheckGraspReachabilityGoal (<CheckGraspReachabilityGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckGraspReachabilityGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckGraspReachabilityGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<CheckGraspReachabilityGoal> is deprecated: use graspit_msgs-msg:CheckGraspReachabilityGoal instead.")))

(cl:ensure-generic-function 'grasp-val :lambda-list '(m))
(cl:defmethod grasp-val ((m <CheckGraspReachabilityGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:grasp-val is deprecated.  Use graspit_msgs-msg:grasp instead.")
  (grasp m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckGraspReachabilityGoal>) ostream)
  "Serializes a message object of type '<CheckGraspReachabilityGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'grasp) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckGraspReachabilityGoal>) istream)
  "Deserializes a message object of type '<CheckGraspReachabilityGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'grasp) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckGraspReachabilityGoal>)))
  "Returns string type for a message object of type '<CheckGraspReachabilityGoal>"
  "graspit_msgs/CheckGraspReachabilityGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckGraspReachabilityGoal)))
  "Returns string type for a message object of type 'CheckGraspReachabilityGoal"
  "graspit_msgs/CheckGraspReachabilityGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckGraspReachabilityGoal>)))
  "Returns md5sum for a message object of type '<CheckGraspReachabilityGoal>"
  "841666638cd8e1dc27b6c550bd4441af")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckGraspReachabilityGoal)))
  "Returns md5sum for a message object of type 'CheckGraspReachabilityGoal"
  "841666638cd8e1dc27b6c550bd4441af")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckGraspReachabilityGoal>)))
  "Returns full string definition for message of type '<CheckGraspReachabilityGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%graspit_msgs/Grasp grasp~%~%================================================================================~%MSG: graspit_msgs/Grasp~%string object_name~%float64 epsilon_quality~%float64 volume_quality~%float64[] secondary_qualities~%int32 grasp_source~%int32 grasp_group~%int32 grasp_type~%int32 grasp_id~%geometry_msgs/Pose pre_grasp_pose~%geometry_msgs/Pose final_grasp_pose~%float64[] pre_grasp_dof~%float64[] final_grasp_dof~%#geometry_msgs/Pose demonstration_pose~%~%int32 TYPE_UNKNOWN = 1~%int32 TYPE_FINGERTIP = 2~%int32 TYPE_POWER_GRASP = 3        # free grasp~%int32 TYPE_TABLECONTACT_GRASP = 4 # finger will make contact w/ table~%int32 SPREAD_DOF=0~%int32 FINGER_1_DOF=1~%int32 FINGER_2_DOF=2~%int32 FINGER_3_DOF=3~%int32 SOURCE_EIGENGRASPS=1~%int32 SOURCE_HUMAN=2~%int32 SOURCE_HUMAN_REFINED=3~%int32 SOURCE_TABLETOP_ALIGNED=7~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckGraspReachabilityGoal)))
  "Returns full string definition for message of type 'CheckGraspReachabilityGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%graspit_msgs/Grasp grasp~%~%================================================================================~%MSG: graspit_msgs/Grasp~%string object_name~%float64 epsilon_quality~%float64 volume_quality~%float64[] secondary_qualities~%int32 grasp_source~%int32 grasp_group~%int32 grasp_type~%int32 grasp_id~%geometry_msgs/Pose pre_grasp_pose~%geometry_msgs/Pose final_grasp_pose~%float64[] pre_grasp_dof~%float64[] final_grasp_dof~%#geometry_msgs/Pose demonstration_pose~%~%int32 TYPE_UNKNOWN = 1~%int32 TYPE_FINGERTIP = 2~%int32 TYPE_POWER_GRASP = 3        # free grasp~%int32 TYPE_TABLECONTACT_GRASP = 4 # finger will make contact w/ table~%int32 SPREAD_DOF=0~%int32 FINGER_1_DOF=1~%int32 FINGER_2_DOF=2~%int32 FINGER_3_DOF=3~%int32 SOURCE_EIGENGRASPS=1~%int32 SOURCE_HUMAN=2~%int32 SOURCE_HUMAN_REFINED=3~%int32 SOURCE_TABLETOP_ALIGNED=7~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckGraspReachabilityGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'grasp))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckGraspReachabilityGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckGraspReachabilityGoal
    (cl:cons ':grasp (grasp msg))
))
