; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude CheckGraspReachabilityResult.msg.html

(cl:defclass <CheckGraspReachabilityResult> (roslisp-msg-protocol:ros-message)
  ((isPossible
    :reader isPossible
    :initarg :isPossible
    :type cl:boolean
    :initform cl:nil)
   (grasp_id
    :reader grasp_id
    :initarg :grasp_id
    :type cl:integer
    :initform 0))
)

(cl:defclass CheckGraspReachabilityResult (<CheckGraspReachabilityResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckGraspReachabilityResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckGraspReachabilityResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<CheckGraspReachabilityResult> is deprecated: use graspit_msgs-msg:CheckGraspReachabilityResult instead.")))

(cl:ensure-generic-function 'isPossible-val :lambda-list '(m))
(cl:defmethod isPossible-val ((m <CheckGraspReachabilityResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:isPossible-val is deprecated.  Use graspit_msgs-msg:isPossible instead.")
  (isPossible m))

(cl:ensure-generic-function 'grasp_id-val :lambda-list '(m))
(cl:defmethod grasp_id-val ((m <CheckGraspReachabilityResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:grasp_id-val is deprecated.  Use graspit_msgs-msg:grasp_id instead.")
  (grasp_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckGraspReachabilityResult>) ostream)
  "Serializes a message object of type '<CheckGraspReachabilityResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'isPossible) 1 0)) ostream)
  (cl:let* ((signed (cl:slot-value msg 'grasp_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckGraspReachabilityResult>) istream)
  "Deserializes a message object of type '<CheckGraspReachabilityResult>"
    (cl:setf (cl:slot-value msg 'isPossible) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'grasp_id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckGraspReachabilityResult>)))
  "Returns string type for a message object of type '<CheckGraspReachabilityResult>"
  "graspit_msgs/CheckGraspReachabilityResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckGraspReachabilityResult)))
  "Returns string type for a message object of type 'CheckGraspReachabilityResult"
  "graspit_msgs/CheckGraspReachabilityResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckGraspReachabilityResult>)))
  "Returns md5sum for a message object of type '<CheckGraspReachabilityResult>"
  "30778d17abcbeb0ad51e654b670ff523")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckGraspReachabilityResult)))
  "Returns md5sum for a message object of type 'CheckGraspReachabilityResult"
  "30778d17abcbeb0ad51e654b670ff523")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckGraspReachabilityResult>)))
  "Returns full string definition for message of type '<CheckGraspReachabilityResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool isPossible~%int32 grasp_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckGraspReachabilityResult)))
  "Returns full string definition for message of type 'CheckGraspReachabilityResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool isPossible~%int32 grasp_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckGraspReachabilityResult>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckGraspReachabilityResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckGraspReachabilityResult
    (cl:cons ':isPossible (isPossible msg))
    (cl:cons ':grasp_id (grasp_id msg))
))
