; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude GraspExecutionFeedback.msg.html

(cl:defclass <GraspExecutionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GraspExecutionFeedback (<GraspExecutionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspExecutionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspExecutionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<GraspExecutionFeedback> is deprecated: use graspit_msgs-msg:GraspExecutionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspExecutionFeedback>) ostream)
  "Serializes a message object of type '<GraspExecutionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspExecutionFeedback>) istream)
  "Deserializes a message object of type '<GraspExecutionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspExecutionFeedback>)))
  "Returns string type for a message object of type '<GraspExecutionFeedback>"
  "graspit_msgs/GraspExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspExecutionFeedback)))
  "Returns string type for a message object of type 'GraspExecutionFeedback"
  "graspit_msgs/GraspExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspExecutionFeedback>)))
  "Returns md5sum for a message object of type '<GraspExecutionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspExecutionFeedback)))
  "Returns md5sum for a message object of type 'GraspExecutionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspExecutionFeedback>)))
  "Returns full string definition for message of type '<GraspExecutionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspExecutionFeedback)))
  "Returns full string definition for message of type 'GraspExecutionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspExecutionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspExecutionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspExecutionFeedback
))
