; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude GraspExecutionResult.msg.html

(cl:defclass <GraspExecutionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GraspExecutionResult (<GraspExecutionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspExecutionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspExecutionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<GraspExecutionResult> is deprecated: use graspit_msgs-msg:GraspExecutionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <GraspExecutionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:success-val is deprecated.  Use graspit_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspExecutionResult>) ostream)
  "Serializes a message object of type '<GraspExecutionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspExecutionResult>) istream)
  "Deserializes a message object of type '<GraspExecutionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspExecutionResult>)))
  "Returns string type for a message object of type '<GraspExecutionResult>"
  "graspit_msgs/GraspExecutionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspExecutionResult)))
  "Returns string type for a message object of type 'GraspExecutionResult"
  "graspit_msgs/GraspExecutionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspExecutionResult>)))
  "Returns md5sum for a message object of type '<GraspExecutionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspExecutionResult)))
  "Returns md5sum for a message object of type 'GraspExecutionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspExecutionResult>)))
  "Returns full string definition for message of type '<GraspExecutionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspExecutionResult)))
  "Returns full string definition for message of type 'GraspExecutionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspExecutionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspExecutionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspExecutionResult
    (cl:cons ':success (success msg))
))
