; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude ManualGoal.msg.html

(cl:defclass <ManualGoal> (roslisp-msg-protocol:ros-message)
  ((manualinfo
    :reader manualinfo
    :initarg :manualinfo
    :type graspit_msgs-msg:ManualInfo
    :initform (cl:make-instance 'graspit_msgs-msg:ManualInfo)))
)

(cl:defclass ManualGoal (<ManualGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ManualGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ManualGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<ManualGoal> is deprecated: use graspit_msgs-msg:ManualGoal instead.")))

(cl:ensure-generic-function 'manualinfo-val :lambda-list '(m))
(cl:defmethod manualinfo-val ((m <ManualGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:manualinfo-val is deprecated.  Use graspit_msgs-msg:manualinfo instead.")
  (manualinfo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ManualGoal>) ostream)
  "Serializes a message object of type '<ManualGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'manualinfo) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ManualGoal>) istream)
  "Deserializes a message object of type '<ManualGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'manualinfo) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ManualGoal>)))
  "Returns string type for a message object of type '<ManualGoal>"
  "graspit_msgs/ManualGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ManualGoal)))
  "Returns string type for a message object of type 'ManualGoal"
  "graspit_msgs/ManualGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ManualGoal>)))
  "Returns md5sum for a message object of type '<ManualGoal>"
  "992f694269d4b617c571b52870412fae")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ManualGoal)))
  "Returns md5sum for a message object of type 'ManualGoal"
  "992f694269d4b617c571b52870412fae")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ManualGoal>)))
  "Returns full string definition for message of type '<ManualGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%ManualInfo manualinfo~%~%================================================================================~%MSG: graspit_msgs/ManualInfo~%int32 axis~%int32 direction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ManualGoal)))
  "Returns full string definition for message of type 'ManualGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%ManualInfo manualinfo~%~%================================================================================~%MSG: graspit_msgs/ManualInfo~%int32 axis~%int32 direction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ManualGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'manualinfo))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ManualGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ManualGoal
    (cl:cons ':manualinfo (manualinfo msg))
))
