; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude ManualFeedback.msg.html

(cl:defclass <ManualFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ManualFeedback (<ManualFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ManualFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ManualFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<ManualFeedback> is deprecated: use graspit_msgs-msg:ManualFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ManualFeedback>) ostream)
  "Serializes a message object of type '<ManualFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ManualFeedback>) istream)
  "Deserializes a message object of type '<ManualFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ManualFeedback>)))
  "Returns string type for a message object of type '<ManualFeedback>"
  "graspit_msgs/ManualFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ManualFeedback)))
  "Returns string type for a message object of type 'ManualFeedback"
  "graspit_msgs/ManualFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ManualFeedback>)))
  "Returns md5sum for a message object of type '<ManualFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ManualFeedback)))
  "Returns md5sum for a message object of type 'ManualFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ManualFeedback>)))
  "Returns full string definition for message of type '<ManualFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ManualFeedback)))
  "Returns full string definition for message of type 'ManualFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ManualFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ManualFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ManualFeedback
))
