; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude ManualResult.msg.html

(cl:defclass <ManualResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ManualResult (<ManualResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ManualResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ManualResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<ManualResult> is deprecated: use graspit_msgs-msg:ManualResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <ManualResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:success-val is deprecated.  Use graspit_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ManualResult>) ostream)
  "Serializes a message object of type '<ManualResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ManualResult>) istream)
  "Deserializes a message object of type '<ManualResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ManualResult>)))
  "Returns string type for a message object of type '<ManualResult>"
  "graspit_msgs/ManualResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ManualResult)))
  "Returns string type for a message object of type 'ManualResult"
  "graspit_msgs/ManualResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ManualResult>)))
  "Returns md5sum for a message object of type '<ManualResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ManualResult)))
  "Returns md5sum for a message object of type 'ManualResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ManualResult>)))
  "Returns full string definition for message of type '<ManualResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ManualResult)))
  "Returns full string definition for message of type 'ManualResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ManualResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ManualResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ManualResult
    (cl:cons ':success (success msg))
))
