; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude RotationGoal.msg.html

(cl:defclass <RotationGoal> (roslisp-msg-protocol:ros-message)
  ((rotationinfo
    :reader rotationinfo
    :initarg :rotationinfo
    :type graspit_msgs-msg:RotationInfo
    :initform (cl:make-instance 'graspit_msgs-msg:RotationInfo)))
)

(cl:defclass RotationGoal (<RotationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<RotationGoal> is deprecated: use graspit_msgs-msg:RotationGoal instead.")))

(cl:ensure-generic-function 'rotationinfo-val :lambda-list '(m))
(cl:defmethod rotationinfo-val ((m <RotationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:rotationinfo-val is deprecated.  Use graspit_msgs-msg:rotationinfo instead.")
  (rotationinfo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotationGoal>) ostream)
  "Serializes a message object of type '<RotationGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'rotationinfo) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotationGoal>) istream)
  "Deserializes a message object of type '<RotationGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'rotationinfo) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotationGoal>)))
  "Returns string type for a message object of type '<RotationGoal>"
  "graspit_msgs/RotationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotationGoal)))
  "Returns string type for a message object of type 'RotationGoal"
  "graspit_msgs/RotationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotationGoal>)))
  "Returns md5sum for a message object of type '<RotationGoal>"
  "a8d1a9210281eae4c859074d3c9d7580")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotationGoal)))
  "Returns md5sum for a message object of type 'RotationGoal"
  "a8d1a9210281eae4c859074d3c9d7580")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotationGoal>)))
  "Returns full string definition for message of type '<RotationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%RotationInfo rotationinfo~%~%================================================================================~%MSG: graspit_msgs/RotationInfo~%int32 axis~%int32 direction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotationGoal)))
  "Returns full string definition for message of type 'RotationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%RotationInfo rotationinfo~%~%================================================================================~%MSG: graspit_msgs/RotationInfo~%int32 axis~%int32 direction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotationGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'rotationinfo))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RotationGoal
    (cl:cons ':rotationinfo (rotationinfo msg))
))
