; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude RotationFeedback.msg.html

(cl:defclass <RotationFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RotationFeedback (<RotationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<RotationFeedback> is deprecated: use graspit_msgs-msg:RotationFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotationFeedback>) ostream)
  "Serializes a message object of type '<RotationFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotationFeedback>) istream)
  "Deserializes a message object of type '<RotationFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotationFeedback>)))
  "Returns string type for a message object of type '<RotationFeedback>"
  "graspit_msgs/RotationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotationFeedback)))
  "Returns string type for a message object of type 'RotationFeedback"
  "graspit_msgs/RotationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotationFeedback>)))
  "Returns md5sum for a message object of type '<RotationFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotationFeedback)))
  "Returns md5sum for a message object of type 'RotationFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotationFeedback>)))
  "Returns full string definition for message of type '<RotationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotationFeedback)))
  "Returns full string definition for message of type 'RotationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotationFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RotationFeedback
))
