; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude RunObjectRecognitionFeedback.msg.html

(cl:defclass <RunObjectRecognitionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunObjectRecognitionFeedback (<RunObjectRecognitionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunObjectRecognitionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunObjectRecognitionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<RunObjectRecognitionFeedback> is deprecated: use graspit_msgs-msg:RunObjectRecognitionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunObjectRecognitionFeedback>) ostream)
  "Serializes a message object of type '<RunObjectRecognitionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunObjectRecognitionFeedback>) istream)
  "Deserializes a message object of type '<RunObjectRecognitionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunObjectRecognitionFeedback>)))
  "Returns string type for a message object of type '<RunObjectRecognitionFeedback>"
  "graspit_msgs/RunObjectRecognitionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunObjectRecognitionFeedback)))
  "Returns string type for a message object of type 'RunObjectRecognitionFeedback"
  "graspit_msgs/RunObjectRecognitionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunObjectRecognitionFeedback>)))
  "Returns md5sum for a message object of type '<RunObjectRecognitionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunObjectRecognitionFeedback)))
  "Returns md5sum for a message object of type 'RunObjectRecognitionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunObjectRecognitionFeedback>)))
  "Returns full string definition for message of type '<RunObjectRecognitionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunObjectRecognitionFeedback)))
  "Returns full string definition for message of type 'RunObjectRecognitionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunObjectRecognitionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunObjectRecognitionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RunObjectRecognitionFeedback
))
