; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude RunObjectRecognitionGoal.msg.html

(cl:defclass <RunObjectRecognitionGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunObjectRecognitionGoal (<RunObjectRecognitionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunObjectRecognitionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunObjectRecognitionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<RunObjectRecognitionGoal> is deprecated: use graspit_msgs-msg:RunObjectRecognitionGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunObjectRecognitionGoal>) ostream)
  "Serializes a message object of type '<RunObjectRecognitionGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunObjectRecognitionGoal>) istream)
  "Deserializes a message object of type '<RunObjectRecognitionGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunObjectRecognitionGoal>)))
  "Returns string type for a message object of type '<RunObjectRecognitionGoal>"
  "graspit_msgs/RunObjectRecognitionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunObjectRecognitionGoal)))
  "Returns string type for a message object of type 'RunObjectRecognitionGoal"
  "graspit_msgs/RunObjectRecognitionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunObjectRecognitionGoal>)))
  "Returns md5sum for a message object of type '<RunObjectRecognitionGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunObjectRecognitionGoal)))
  "Returns md5sum for a message object of type 'RunObjectRecognitionGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunObjectRecognitionGoal>)))
  "Returns full string definition for message of type '<RunObjectRecognitionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunObjectRecognitionGoal)))
  "Returns full string definition for message of type 'RunObjectRecognitionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunObjectRecognitionGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunObjectRecognitionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RunObjectRecognitionGoal
))
