; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude ToggleGripperFeedback.msg.html

(cl:defclass <ToggleGripperFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ToggleGripperFeedback (<ToggleGripperFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ToggleGripperFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ToggleGripperFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<ToggleGripperFeedback> is deprecated: use graspit_msgs-msg:ToggleGripperFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ToggleGripperFeedback>) ostream)
  "Serializes a message object of type '<ToggleGripperFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ToggleGripperFeedback>) istream)
  "Deserializes a message object of type '<ToggleGripperFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ToggleGripperFeedback>)))
  "Returns string type for a message object of type '<ToggleGripperFeedback>"
  "graspit_msgs/ToggleGripperFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ToggleGripperFeedback)))
  "Returns string type for a message object of type 'ToggleGripperFeedback"
  "graspit_msgs/ToggleGripperFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ToggleGripperFeedback>)))
  "Returns md5sum for a message object of type '<ToggleGripperFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ToggleGripperFeedback)))
  "Returns md5sum for a message object of type 'ToggleGripperFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ToggleGripperFeedback>)))
  "Returns full string definition for message of type '<ToggleGripperFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ToggleGripperFeedback)))
  "Returns full string definition for message of type 'ToggleGripperFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ToggleGripperFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ToggleGripperFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ToggleGripperFeedback
))
