; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude ToggleGripperGoal.msg.html

(cl:defclass <ToggleGripperGoal> (roslisp-msg-protocol:ros-message)
  ((toggle
    :reader toggle
    :initarg :toggle
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ToggleGripperGoal (<ToggleGripperGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ToggleGripperGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ToggleGripperGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<ToggleGripperGoal> is deprecated: use graspit_msgs-msg:ToggleGripperGoal instead.")))

(cl:ensure-generic-function 'toggle-val :lambda-list '(m))
(cl:defmethod toggle-val ((m <ToggleGripperGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:toggle-val is deprecated.  Use graspit_msgs-msg:toggle instead.")
  (toggle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ToggleGripperGoal>) ostream)
  "Serializes a message object of type '<ToggleGripperGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'toggle) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ToggleGripperGoal>) istream)
  "Deserializes a message object of type '<ToggleGripperGoal>"
    (cl:setf (cl:slot-value msg 'toggle) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ToggleGripperGoal>)))
  "Returns string type for a message object of type '<ToggleGripperGoal>"
  "graspit_msgs/ToggleGripperGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ToggleGripperGoal)))
  "Returns string type for a message object of type 'ToggleGripperGoal"
  "graspit_msgs/ToggleGripperGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ToggleGripperGoal>)))
  "Returns md5sum for a message object of type '<ToggleGripperGoal>"
  "301e9e6fc0ec5b2acb90ccde2488159e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ToggleGripperGoal)))
  "Returns md5sum for a message object of type 'ToggleGripperGoal"
  "301e9e6fc0ec5b2acb90ccde2488159e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ToggleGripperGoal>)))
  "Returns full string definition for message of type '<ToggleGripperGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool toggle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ToggleGripperGoal)))
  "Returns full string definition for message of type 'ToggleGripperGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool toggle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ToggleGripperGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ToggleGripperGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ToggleGripperGoal
    (cl:cons ':toggle (toggle msg))
))
