; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude TranslationGoal.msg.html

(cl:defclass <TranslationGoal> (roslisp-msg-protocol:ros-message)
  ((translationinfo
    :reader translationinfo
    :initarg :translationinfo
    :type graspit_msgs-msg:TranslationInfo
    :initform (cl:make-instance 'graspit_msgs-msg:TranslationInfo)))
)

(cl:defclass TranslationGoal (<TranslationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TranslationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TranslationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<TranslationGoal> is deprecated: use graspit_msgs-msg:TranslationGoal instead.")))

(cl:ensure-generic-function 'translationinfo-val :lambda-list '(m))
(cl:defmethod translationinfo-val ((m <TranslationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:translationinfo-val is deprecated.  Use graspit_msgs-msg:translationinfo instead.")
  (translationinfo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TranslationGoal>) ostream)
  "Serializes a message object of type '<TranslationGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'translationinfo) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TranslationGoal>) istream)
  "Deserializes a message object of type '<TranslationGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'translationinfo) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TranslationGoal>)))
  "Returns string type for a message object of type '<TranslationGoal>"
  "graspit_msgs/TranslationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TranslationGoal)))
  "Returns string type for a message object of type 'TranslationGoal"
  "graspit_msgs/TranslationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TranslationGoal>)))
  "Returns md5sum for a message object of type '<TranslationGoal>"
  "aa424b9a57104e87b8d66bb27b73a39f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TranslationGoal)))
  "Returns md5sum for a message object of type 'TranslationGoal"
  "aa424b9a57104e87b8d66bb27b73a39f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TranslationGoal>)))
  "Returns full string definition for message of type '<TranslationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%TranslationInfo translationinfo~%~%================================================================================~%MSG: graspit_msgs/TranslationInfo~%string axis~%string direction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TranslationGoal)))
  "Returns full string definition for message of type 'TranslationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%TranslationInfo translationinfo~%~%================================================================================~%MSG: graspit_msgs/TranslationInfo~%string axis~%string direction~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TranslationGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'translationinfo))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TranslationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TranslationGoal
    (cl:cons ':translationinfo (translationinfo msg))
))
