; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude TranslationResult.msg.html

(cl:defclass <TranslationResult> (roslisp-msg-protocol:ros-message)
  ((successfulMove
    :reader successfulMove
    :initarg :successfulMove
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass TranslationResult (<TranslationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TranslationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TranslationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<TranslationResult> is deprecated: use graspit_msgs-msg:TranslationResult instead.")))

(cl:ensure-generic-function 'successfulMove-val :lambda-list '(m))
(cl:defmethod successfulMove-val ((m <TranslationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_msgs-msg:successfulMove-val is deprecated.  Use graspit_msgs-msg:successfulMove instead.")
  (successfulMove m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TranslationResult>) ostream)
  "Serializes a message object of type '<TranslationResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'successfulMove) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TranslationResult>) istream)
  "Deserializes a message object of type '<TranslationResult>"
    (cl:setf (cl:slot-value msg 'successfulMove) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TranslationResult>)))
  "Returns string type for a message object of type '<TranslationResult>"
  "graspit_msgs/TranslationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TranslationResult)))
  "Returns string type for a message object of type 'TranslationResult"
  "graspit_msgs/TranslationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TranslationResult>)))
  "Returns md5sum for a message object of type '<TranslationResult>"
  "eda23447ac7f8ea035bb917cf3e3c56e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TranslationResult)))
  "Returns md5sum for a message object of type 'TranslationResult"
  "eda23447ac7f8ea035bb917cf3e3c56e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TranslationResult>)))
  "Returns full string definition for message of type '<TranslationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool successfulMove~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TranslationResult)))
  "Returns full string definition for message of type 'TranslationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool successfulMove~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TranslationResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TranslationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TranslationResult
    (cl:cons ':successfulMove (successfulMove msg))
))
