; Auto-generated. Do not edit!


(cl:in-package graspit_msgs-msg)


;//! \htmlinclude TranslationFeedback.msg.html

(cl:defclass <TranslationFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TranslationFeedback (<TranslationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TranslationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TranslationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_msgs-msg:<TranslationFeedback> is deprecated: use graspit_msgs-msg:TranslationFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TranslationFeedback>) ostream)
  "Serializes a message object of type '<TranslationFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TranslationFeedback>) istream)
  "Deserializes a message object of type '<TranslationFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TranslationFeedback>)))
  "Returns string type for a message object of type '<TranslationFeedback>"
  "graspit_msgs/TranslationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TranslationFeedback)))
  "Returns string type for a message object of type 'TranslationFeedback"
  "graspit_msgs/TranslationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TranslationFeedback>)))
  "Returns md5sum for a message object of type '<TranslationFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TranslationFeedback)))
  "Returns md5sum for a message object of type 'TranslationFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TranslationFeedback>)))
  "Returns full string definition for message of type '<TranslationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TranslationFeedback)))
  "Returns full string definition for message of type 'TranslationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TranslationFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TranslationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TranslationFeedback
))
