(cl:in-package graspit_interface-msg)
(cl:export '(GRASPABLE_BODY_ID-VAL
          GRASPABLE_BODY_ID
          POSE-VAL
          POSE
          DOFS-VAL
          DOFS
          EPSILON_QUALITY-VAL
          EPSILON_QUALITY
          VOLUME_QUALITY-VAL
          VOLUME_QUALITY
          APPROACH_DIRECTION-VAL
          APPROACH_DIRECTION
          OBJECT_NAME-VAL
          OBJECT_NAME
          GRASP_ID-VAL
          GRASP_ID
          SECONDARY_QUALITIES-VAL
          SECONDARY_QUALITIES
          GRASP_SOURCE-VAL
          GRASP_SOURCE
          GRASP_GROUP-VAL
          GRASP_GROUP
          GRASP_TYPE-VAL
          GRASP_TYPE
          PRE_GRASP_POSE-VAL
          PRE_GRASP_POSE
          FINAL_GRASP_POSE-VAL
          FINAL_GRASP_POSE
          PRE_GRASP_DOF-VAL
          PRE_GRASP_DOF
          FINAL_GRASP_DOF-VAL
          FINAL_GRASP_DOF
))