; Auto-generated. Do not edit!


(cl:in-package graspit_interface-msg)


;//! \htmlinclude CheckGraspReachabilityFeedback.msg.html

(cl:defclass <CheckGraspReachabilityFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CheckGraspReachabilityFeedback (<CheckGraspReachabilityFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckGraspReachabilityFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckGraspReachabilityFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_interface-msg:<CheckGraspReachabilityFeedback> is deprecated: use graspit_interface-msg:CheckGraspReachabilityFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckGraspReachabilityFeedback>) ostream)
  "Serializes a message object of type '<CheckGraspReachabilityFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckGraspReachabilityFeedback>) istream)
  "Deserializes a message object of type '<CheckGraspReachabilityFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckGraspReachabilityFeedback>)))
  "Returns string type for a message object of type '<CheckGraspReachabilityFeedback>"
  "graspit_interface/CheckGraspReachabilityFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckGraspReachabilityFeedback)))
  "Returns string type for a message object of type 'CheckGraspReachabilityFeedback"
  "graspit_interface/CheckGraspReachabilityFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckGraspReachabilityFeedback>)))
  "Returns md5sum for a message object of type '<CheckGraspReachabilityFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckGraspReachabilityFeedback)))
  "Returns md5sum for a message object of type 'CheckGraspReachabilityFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckGraspReachabilityFeedback>)))
  "Returns full string definition for message of type '<CheckGraspReachabilityFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckGraspReachabilityFeedback)))
  "Returns full string definition for message of type 'CheckGraspReachabilityFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckGraspReachabilityFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckGraspReachabilityFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckGraspReachabilityFeedback
))
