; Auto-generated. Do not edit!


(cl:in-package graspit_interface-msg)


;//! \htmlinclude PlaceExecutionResult.msg.html

(cl:defclass <PlaceExecutionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PlaceExecutionResult (<PlaceExecutionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlaceExecutionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlaceExecutionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_interface-msg:<PlaceExecutionResult> is deprecated: use graspit_interface-msg:PlaceExecutionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <PlaceExecutionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_interface-msg:success-val is deprecated.  Use graspit_interface-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlaceExecutionResult>) ostream)
  "Serializes a message object of type '<PlaceExecutionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlaceExecutionResult>) istream)
  "Deserializes a message object of type '<PlaceExecutionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlaceExecutionResult>)))
  "Returns string type for a message object of type '<PlaceExecutionResult>"
  "graspit_interface/PlaceExecutionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlaceExecutionResult)))
  "Returns string type for a message object of type 'PlaceExecutionResult"
  "graspit_interface/PlaceExecutionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlaceExecutionResult>)))
  "Returns md5sum for a message object of type '<PlaceExecutionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlaceExecutionResult)))
  "Returns md5sum for a message object of type 'PlaceExecutionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlaceExecutionResult>)))
  "Returns full string definition for message of type '<PlaceExecutionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlaceExecutionResult)))
  "Returns full string definition for message of type 'PlaceExecutionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlaceExecutionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlaceExecutionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PlaceExecutionResult
    (cl:cons ':success (success msg))
))
