; Auto-generated. Do not edit!


(cl:in-package graspit_interface-msg)


;//! \htmlinclude PlaceExecutionFeedback.msg.html

(cl:defclass <PlaceExecutionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlaceExecutionFeedback (<PlaceExecutionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlaceExecutionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlaceExecutionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_interface-msg:<PlaceExecutionFeedback> is deprecated: use graspit_interface-msg:PlaceExecutionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlaceExecutionFeedback>) ostream)
  "Serializes a message object of type '<PlaceExecutionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlaceExecutionFeedback>) istream)
  "Deserializes a message object of type '<PlaceExecutionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlaceExecutionFeedback>)))
  "Returns string type for a message object of type '<PlaceExecutionFeedback>"
  "graspit_interface/PlaceExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlaceExecutionFeedback)))
  "Returns string type for a message object of type 'PlaceExecutionFeedback"
  "graspit_interface/PlaceExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlaceExecutionFeedback>)))
  "Returns md5sum for a message object of type '<PlaceExecutionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlaceExecutionFeedback)))
  "Returns md5sum for a message object of type 'PlaceExecutionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlaceExecutionFeedback>)))
  "Returns full string definition for message of type '<PlaceExecutionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlaceExecutionFeedback)))
  "Returns full string definition for message of type 'PlaceExecutionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlaceExecutionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlaceExecutionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlaceExecutionFeedback
))
