; Auto-generated. Do not edit!


(cl:in-package graspit_interface-msg)


;//! \htmlinclude PlanGraspsFeedback.msg.html

(cl:defclass <PlanGraspsFeedback> (roslisp-msg-protocol:ros-message)
  ((current_step
    :reader current_step
    :initarg :current_step
    :type cl:integer
    :initform 0)
   (current_num_grasps
    :reader current_num_grasps
    :initarg :current_num_grasps
    :type cl:integer
    :initform 0))
)

(cl:defclass PlanGraspsFeedback (<PlanGraspsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlanGraspsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlanGraspsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graspit_interface-msg:<PlanGraspsFeedback> is deprecated: use graspit_interface-msg:PlanGraspsFeedback instead.")))

(cl:ensure-generic-function 'current_step-val :lambda-list '(m))
(cl:defmethod current_step-val ((m <PlanGraspsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_interface-msg:current_step-val is deprecated.  Use graspit_interface-msg:current_step instead.")
  (current_step m))

(cl:ensure-generic-function 'current_num_grasps-val :lambda-list '(m))
(cl:defmethod current_num_grasps-val ((m <PlanGraspsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graspit_interface-msg:current_num_grasps-val is deprecated.  Use graspit_interface-msg:current_num_grasps instead.")
  (current_num_grasps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlanGraspsFeedback>) ostream)
  "Serializes a message object of type '<PlanGraspsFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_step)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'current_num_grasps)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlanGraspsFeedback>) istream)
  "Deserializes a message object of type '<PlanGraspsFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_step) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_num_grasps) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlanGraspsFeedback>)))
  "Returns string type for a message object of type '<PlanGraspsFeedback>"
  "graspit_interface/PlanGraspsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlanGraspsFeedback)))
  "Returns string type for a message object of type 'PlanGraspsFeedback"
  "graspit_interface/PlanGraspsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlanGraspsFeedback>)))
  "Returns md5sum for a message object of type '<PlanGraspsFeedback>"
  "04ac0f69e255f7fd23b3c7fcb11a47bf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlanGraspsFeedback)))
  "Returns md5sum for a message object of type 'PlanGraspsFeedback"
  "04ac0f69e255f7fd23b3c7fcb11a47bf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlanGraspsFeedback>)))
  "Returns full string definition for message of type '<PlanGraspsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback ~%int32 current_step~%int32 current_num_grasps~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlanGraspsFeedback)))
  "Returns full string definition for message of type 'PlanGraspsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback ~%int32 current_step~%int32 current_num_grasps~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlanGraspsFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlanGraspsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlanGraspsFeedback
    (cl:cons ':current_step (current_step msg))
    (cl:cons ':current_num_grasps (current_num_grasps msg))
))
