// Generated by gencpp from file graspit_msgs/AnalyzePoseResponse.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_ANALYZEPOSERESPONSE_H
#define GRASPIT_MSGS_MESSAGE_ANALYZEPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_msgs
{
template <class ContainerAllocator>
struct AnalyzePoseResponse_
{
  typedef AnalyzePoseResponse_<ContainerAllocator> Type;

  AnalyzePoseResponse_()
    : success_probability(0.0)  {
    }
  AnalyzePoseResponse_(const ContainerAllocator& _alloc)
    : success_probability(0.0)  {
  (void)_alloc;
    }



   typedef double _success_probability_type;
  _success_probability_type success_probability;




  typedef boost::shared_ptr< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AnalyzePoseResponse_

typedef ::graspit_msgs::AnalyzePoseResponse_<std::allocator<void> > AnalyzePoseResponse;

typedef boost::shared_ptr< ::graspit_msgs::AnalyzePoseResponse > AnalyzePoseResponsePtr;
typedef boost::shared_ptr< ::graspit_msgs::AnalyzePoseResponse const> AnalyzePoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'graspit_msgs': ['/home/masatoshichang/robotics/fetch_ws/src/graspit_msgs/msg', '/home/masatoshichang/robotics/fetch_ws/devel/share/graspit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56c9e385105527ed095de07b9abcf804";
  }

  static const char* value(const ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56c9e385105527edULL;
  static const uint64_t static_value2 = 0x095de07b9abcf804ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_msgs/AnalyzePoseResponse";
  }

  static const char* value(const ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 success_probability\n\
";
  }

  static const char* value(const ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success_probability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnalyzePoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_msgs::AnalyzePoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success_probability: ";
    Printer<double>::stream(s, indent + "  ", v.success_probability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_ANALYZEPOSERESPONSE_H
