// Generated by gencpp from file graspit_msgs/AnalyzePose.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_ANALYZEPOSE_H
#define GRASPIT_MSGS_MESSAGE_ANALYZEPOSE_H

#include <ros/service_traits.h>


#include <graspit_msgs/AnalyzePoseRequest.h>
#include <graspit_msgs/AnalyzePoseResponse.h>


namespace graspit_msgs
{

struct AnalyzePose
{

typedef AnalyzePoseRequest Request;
typedef AnalyzePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnalyzePose
} // namespace graspit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_msgs::AnalyzePose > {
  static const char* value()
  {
    return "79041c90ae0e6c55c5cfef12cac63573";
  }

  static const char* value(const ::graspit_msgs::AnalyzePose&) { return value(); }
};

template<>
struct DataType< ::graspit_msgs::AnalyzePose > {
  static const char* value()
  {
    return "graspit_msgs/AnalyzePose";
  }

  static const char* value(const ::graspit_msgs::AnalyzePose&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_msgs::AnalyzePoseRequest> should match 
// service_traits::MD5Sum< ::graspit_msgs::AnalyzePose > 
template<>
struct MD5Sum< ::graspit_msgs::AnalyzePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::AnalyzePose >::value();
  }
  static const char* value(const ::graspit_msgs::AnalyzePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::AnalyzePoseRequest> should match 
// service_traits::DataType< ::graspit_msgs::AnalyzePose > 
template<>
struct DataType< ::graspit_msgs::AnalyzePoseRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::AnalyzePose >::value();
  }
  static const char* value(const ::graspit_msgs::AnalyzePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_msgs::AnalyzePoseResponse> should match 
// service_traits::MD5Sum< ::graspit_msgs::AnalyzePose > 
template<>
struct MD5Sum< ::graspit_msgs::AnalyzePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::AnalyzePose >::value();
  }
  static const char* value(const ::graspit_msgs::AnalyzePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::AnalyzePoseResponse> should match 
// service_traits::DataType< ::graspit_msgs::AnalyzePose > 
template<>
struct DataType< ::graspit_msgs::AnalyzePoseResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::AnalyzePose >::value();
  }
  static const char* value(const ::graspit_msgs::AnalyzePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_ANALYZEPOSE_H
