// Generated by gencpp from file graspit_msgs/GetCameraOrigin.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_GETCAMERAORIGIN_H
#define GRASPIT_MSGS_MESSAGE_GETCAMERAORIGIN_H

#include <ros/service_traits.h>


#include <graspit_msgs/GetCameraOriginRequest.h>
#include <graspit_msgs/GetCameraOriginResponse.h>


namespace graspit_msgs
{

struct GetCameraOrigin
{

typedef GetCameraOriginRequest Request;
typedef GetCameraOriginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraOrigin
} // namespace graspit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_msgs::GetCameraOrigin > {
  static const char* value()
  {
    return "2eccb8abb2ccbb1de388429ce1a0fdec";
  }

  static const char* value(const ::graspit_msgs::GetCameraOrigin&) { return value(); }
};

template<>
struct DataType< ::graspit_msgs::GetCameraOrigin > {
  static const char* value()
  {
    return "graspit_msgs/GetCameraOrigin";
  }

  static const char* value(const ::graspit_msgs::GetCameraOrigin&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_msgs::GetCameraOriginRequest> should match 
// service_traits::MD5Sum< ::graspit_msgs::GetCameraOrigin > 
template<>
struct MD5Sum< ::graspit_msgs::GetCameraOriginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::GetCameraOrigin >::value();
  }
  static const char* value(const ::graspit_msgs::GetCameraOriginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::GetCameraOriginRequest> should match 
// service_traits::DataType< ::graspit_msgs::GetCameraOrigin > 
template<>
struct DataType< ::graspit_msgs::GetCameraOriginRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::GetCameraOrigin >::value();
  }
  static const char* value(const ::graspit_msgs::GetCameraOriginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_msgs::GetCameraOriginResponse> should match 
// service_traits::MD5Sum< ::graspit_msgs::GetCameraOrigin > 
template<>
struct MD5Sum< ::graspit_msgs::GetCameraOriginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::GetCameraOrigin >::value();
  }
  static const char* value(const ::graspit_msgs::GetCameraOriginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::GetCameraOriginResponse> should match 
// service_traits::DataType< ::graspit_msgs::GetCameraOrigin > 
template<>
struct DataType< ::graspit_msgs::GetCameraOriginResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::GetCameraOrigin >::value();
  }
  static const char* value(const ::graspit_msgs::GetCameraOriginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_GETCAMERAORIGIN_H
