// Generated by gencpp from file graspit_msgs/GetObjectInfo.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_GETOBJECTINFO_H
#define GRASPIT_MSGS_MESSAGE_GETOBJECTINFO_H

#include <ros/service_traits.h>


#include <graspit_msgs/GetObjectInfoRequest.h>
#include <graspit_msgs/GetObjectInfoResponse.h>


namespace graspit_msgs
{

struct GetObjectInfo
{

typedef GetObjectInfoRequest Request;
typedef GetObjectInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectInfo
} // namespace graspit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_msgs::GetObjectInfo > {
  static const char* value()
  {
    return "bdc8d8269b448089f6ea6aa337b990f2";
  }

  static const char* value(const ::graspit_msgs::GetObjectInfo&) { return value(); }
};

template<>
struct DataType< ::graspit_msgs::GetObjectInfo > {
  static const char* value()
  {
    return "graspit_msgs/GetObjectInfo";
  }

  static const char* value(const ::graspit_msgs::GetObjectInfo&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfoRequest> should match 
// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfo > 
template<>
struct MD5Sum< ::graspit_msgs::GetObjectInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::GetObjectInfoRequest> should match 
// service_traits::DataType< ::graspit_msgs::GetObjectInfo > 
template<>
struct DataType< ::graspit_msgs::GetObjectInfoRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfoResponse> should match 
// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfo > 
template<>
struct MD5Sum< ::graspit_msgs::GetObjectInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::GetObjectInfoResponse> should match 
// service_traits::DataType< ::graspit_msgs::GetObjectInfo > 
template<>
struct DataType< ::graspit_msgs::GetObjectInfoResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_GETOBJECTINFO_H
