// Generated by gencpp from file graspit_msgs/Grasp.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_GRASP_H
#define GRASPIT_MSGS_MESSAGE_GRASP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace graspit_msgs
{
template <class ContainerAllocator>
struct Grasp_
{
  typedef Grasp_<ContainerAllocator> Type;

  Grasp_()
    : object_name()
    , epsilon_quality(0.0)
    , volume_quality(0.0)
    , secondary_qualities()
    , grasp_source(0)
    , grasp_group(0)
    , grasp_type(0)
    , grasp_id(0)
    , pre_grasp_pose()
    , final_grasp_pose()
    , pre_grasp_dof()
    , final_grasp_dof()  {
    }
  Grasp_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , epsilon_quality(0.0)
    , volume_quality(0.0)
    , secondary_qualities(_alloc)
    , grasp_source(0)
    , grasp_group(0)
    , grasp_type(0)
    , grasp_id(0)
    , pre_grasp_pose(_alloc)
    , final_grasp_pose(_alloc)
    , pre_grasp_dof(_alloc)
    , final_grasp_dof(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;

   typedef double _epsilon_quality_type;
  _epsilon_quality_type epsilon_quality;

   typedef double _volume_quality_type;
  _volume_quality_type volume_quality;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _secondary_qualities_type;
  _secondary_qualities_type secondary_qualities;

   typedef int32_t _grasp_source_type;
  _grasp_source_type grasp_source;

   typedef int32_t _grasp_group_type;
  _grasp_group_type grasp_group;

   typedef int32_t _grasp_type_type;
  _grasp_type_type grasp_type;

   typedef int32_t _grasp_id_type;
  _grasp_id_type grasp_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pre_grasp_pose_type;
  _pre_grasp_pose_type pre_grasp_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _final_grasp_pose_type;
  _final_grasp_pose_type final_grasp_pose;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pre_grasp_dof_type;
  _pre_grasp_dof_type pre_grasp_dof;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _final_grasp_dof_type;
  _final_grasp_dof_type final_grasp_dof;


    enum { TYPE_UNKNOWN = 1 };
     enum { TYPE_FINGERTIP = 2 };
     enum { TYPE_POWER_GRASP = 3 };
     enum { TYPE_TABLECONTACT_GRASP = 4 };
     enum { SPREAD_DOF = 0 };
     enum { FINGER_1_DOF = 1 };
     enum { FINGER_2_DOF = 2 };
     enum { FINGER_3_DOF = 3 };
     enum { SOURCE_EIGENGRASPS = 1 };
     enum { SOURCE_HUMAN = 2 };
     enum { SOURCE_HUMAN_REFINED = 3 };
     enum { SOURCE_TABLETOP_ALIGNED = 7 };
 

  typedef boost::shared_ptr< ::graspit_msgs::Grasp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_msgs::Grasp_<ContainerAllocator> const> ConstPtr;

}; // struct Grasp_

typedef ::graspit_msgs::Grasp_<std::allocator<void> > Grasp;

typedef boost::shared_ptr< ::graspit_msgs::Grasp > GraspPtr;
typedef boost::shared_ptr< ::graspit_msgs::Grasp const> GraspConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_msgs::Grasp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_msgs::Grasp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'graspit_msgs': ['/home/masatoshichang/robotics/fetch_ws/src/graspit_msgs/msg', '/home/masatoshichang/robotics/fetch_ws/devel/share/graspit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::Grasp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::Grasp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::Grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::Grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::Grasp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::Grasp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_msgs::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f1d62a4276a6ddd47b908f7e4322d40";
  }

  static const char* value(const ::graspit_msgs::Grasp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f1d62a4276a6dddULL;
  static const uint64_t static_value2 = 0x47b908f7e4322d40ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_msgs::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_msgs/Grasp";
  }

  static const char* value(const ::graspit_msgs::Grasp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_msgs::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n\
float64 epsilon_quality\n\
float64 volume_quality\n\
float64[] secondary_qualities\n\
int32 grasp_source\n\
int32 grasp_group\n\
int32 grasp_type\n\
int32 grasp_id\n\
geometry_msgs/Pose pre_grasp_pose\n\
geometry_msgs/Pose final_grasp_pose\n\
float64[] pre_grasp_dof\n\
float64[] final_grasp_dof\n\
#geometry_msgs/Pose demonstration_pose\n\
\n\
int32 TYPE_UNKNOWN = 1\n\
int32 TYPE_FINGERTIP = 2\n\
int32 TYPE_POWER_GRASP = 3        # free grasp\n\
int32 TYPE_TABLECONTACT_GRASP = 4 # finger will make contact w/ table\n\
int32 SPREAD_DOF=0\n\
int32 FINGER_1_DOF=1\n\
int32 FINGER_2_DOF=2\n\
int32 FINGER_3_DOF=3\n\
int32 SOURCE_EIGENGRASPS=1\n\
int32 SOURCE_HUMAN=2\n\
int32 SOURCE_HUMAN_REFINED=3\n\
int32 SOURCE_TABLETOP_ALIGNED=7\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::graspit_msgs::Grasp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_msgs::Grasp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.epsilon_quality);
      stream.next(m.volume_quality);
      stream.next(m.secondary_qualities);
      stream.next(m.grasp_source);
      stream.next(m.grasp_group);
      stream.next(m.grasp_type);
      stream.next(m.grasp_id);
      stream.next(m.pre_grasp_pose);
      stream.next(m.final_grasp_pose);
      stream.next(m.pre_grasp_dof);
      stream.next(m.final_grasp_dof);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Grasp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_msgs::Grasp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_msgs::Grasp_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
    s << indent << "epsilon_quality: ";
    Printer<double>::stream(s, indent + "  ", v.epsilon_quality);
    s << indent << "volume_quality: ";
    Printer<double>::stream(s, indent + "  ", v.volume_quality);
    s << indent << "secondary_qualities[]" << std::endl;
    for (size_t i = 0; i < v.secondary_qualities.size(); ++i)
    {
      s << indent << "  secondary_qualities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.secondary_qualities[i]);
    }
    s << indent << "grasp_source: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grasp_source);
    s << indent << "grasp_group: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grasp_group);
    s << indent << "grasp_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grasp_type);
    s << indent << "grasp_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grasp_id);
    s << indent << "pre_grasp_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pre_grasp_pose);
    s << indent << "final_grasp_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.final_grasp_pose);
    s << indent << "pre_grasp_dof[]" << std::endl;
    for (size_t i = 0; i < v.pre_grasp_dof.size(); ++i)
    {
      s << indent << "  pre_grasp_dof[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pre_grasp_dof[i]);
    }
    s << indent << "final_grasp_dof[]" << std::endl;
    for (size_t i = 0; i < v.final_grasp_dof.size(); ++i)
    {
      s << indent << "  final_grasp_dof[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.final_grasp_dof[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_GRASP_H
