// Generated by gencpp from file graspit_msgs/LocationInfo.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_LOCATIONINFO_H
#define GRASPIT_MSGS_MESSAGE_LOCATIONINFO_H

#include <ros/service_traits.h>


#include <graspit_msgs/LocationInfoRequest.h>
#include <graspit_msgs/LocationInfoResponse.h>


namespace graspit_msgs
{

struct LocationInfo
{

typedef LocationInfoRequest Request;
typedef LocationInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocationInfo
} // namespace graspit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_msgs::LocationInfo > {
  static const char* value()
  {
    return "2f96671305e2fc9024bbb630a95e1cff";
  }

  static const char* value(const ::graspit_msgs::LocationInfo&) { return value(); }
};

template<>
struct DataType< ::graspit_msgs::LocationInfo > {
  static const char* value()
  {
    return "graspit_msgs/LocationInfo";
  }

  static const char* value(const ::graspit_msgs::LocationInfo&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_msgs::LocationInfoRequest> should match 
// service_traits::MD5Sum< ::graspit_msgs::LocationInfo > 
template<>
struct MD5Sum< ::graspit_msgs::LocationInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::LocationInfo >::value();
  }
  static const char* value(const ::graspit_msgs::LocationInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::LocationInfoRequest> should match 
// service_traits::DataType< ::graspit_msgs::LocationInfo > 
template<>
struct DataType< ::graspit_msgs::LocationInfoRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::LocationInfo >::value();
  }
  static const char* value(const ::graspit_msgs::LocationInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_msgs::LocationInfoResponse> should match 
// service_traits::MD5Sum< ::graspit_msgs::LocationInfo > 
template<>
struct MD5Sum< ::graspit_msgs::LocationInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::LocationInfo >::value();
  }
  static const char* value(const ::graspit_msgs::LocationInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::LocationInfoResponse> should match 
// service_traits::DataType< ::graspit_msgs::LocationInfo > 
template<>
struct DataType< ::graspit_msgs::LocationInfoResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::LocationInfo >::value();
  }
  static const char* value(const ::graspit_msgs::LocationInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_LOCATIONINFO_H
