// Generated by gencpp from file graspit_msgs/ManualGoal.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_MANUALGOAL_H
#define GRASPIT_MSGS_MESSAGE_MANUALGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <graspit_msgs/ManualInfo.h>

namespace graspit_msgs
{
template <class ContainerAllocator>
struct ManualGoal_
{
  typedef ManualGoal_<ContainerAllocator> Type;

  ManualGoal_()
    : manualinfo()  {
    }
  ManualGoal_(const ContainerAllocator& _alloc)
    : manualinfo(_alloc)  {
  (void)_alloc;
    }



   typedef  ::graspit_msgs::ManualInfo_<ContainerAllocator>  _manualinfo_type;
  _manualinfo_type manualinfo;




  typedef boost::shared_ptr< ::graspit_msgs::ManualGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_msgs::ManualGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ManualGoal_

typedef ::graspit_msgs::ManualGoal_<std::allocator<void> > ManualGoal;

typedef boost::shared_ptr< ::graspit_msgs::ManualGoal > ManualGoalPtr;
typedef boost::shared_ptr< ::graspit_msgs::ManualGoal const> ManualGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_msgs::ManualGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_msgs::ManualGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'graspit_msgs': ['/home/masatoshichang/robotics/fetch_ws/src/graspit_msgs/msg', '/home/masatoshichang/robotics/fetch_ws/devel/share/graspit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::ManualGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::ManualGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::ManualGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992f694269d4b617c571b52870412fae";
  }

  static const char* value(const ::graspit_msgs::ManualGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992f694269d4b617ULL;
  static const uint64_t static_value2 = 0xc571b52870412faeULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_msgs/ManualGoal";
  }

  static const char* value(const ::graspit_msgs::ManualGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
ManualInfo manualinfo\n\
\n\
================================================================================\n\
MSG: graspit_msgs/ManualInfo\n\
int32 axis\n\
int32 direction\n\
";
  }

  static const char* value(const ::graspit_msgs::ManualGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.manualinfo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManualGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_msgs::ManualGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_msgs::ManualGoal_<ContainerAllocator>& v)
  {
    s << indent << "manualinfo: ";
    s << std::endl;
    Printer< ::graspit_msgs::ManualInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.manualinfo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_MANUALGOAL_H
