// Generated by gencpp from file graspit_msgs/ManualInfo.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_MANUALINFO_H
#define GRASPIT_MSGS_MESSAGE_MANUALINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_msgs
{
template <class ContainerAllocator>
struct ManualInfo_
{
  typedef ManualInfo_<ContainerAllocator> Type;

  ManualInfo_()
    : axis(0)
    , direction(0)  {
    }
  ManualInfo_(const ContainerAllocator& _alloc)
    : axis(0)
    , direction(0)  {
  (void)_alloc;
    }



   typedef int32_t _axis_type;
  _axis_type axis;

   typedef int32_t _direction_type;
  _direction_type direction;




  typedef boost::shared_ptr< ::graspit_msgs::ManualInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_msgs::ManualInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ManualInfo_

typedef ::graspit_msgs::ManualInfo_<std::allocator<void> > ManualInfo;

typedef boost::shared_ptr< ::graspit_msgs::ManualInfo > ManualInfoPtr;
typedef boost::shared_ptr< ::graspit_msgs::ManualInfo const> ManualInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_msgs::ManualInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_msgs::ManualInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'graspit_msgs': ['/home/masatoshichang/robotics/fetch_ws/src/graspit_msgs/msg', '/home/masatoshichang/robotics/fetch_ws/devel/share/graspit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::ManualInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::ManualInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::ManualInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "487430391e4f7bcb6fffca78a6d1435b";
  }

  static const char* value(const ::graspit_msgs::ManualInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x487430391e4f7bcbULL;
  static const uint64_t static_value2 = 0x6fffca78a6d1435bULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_msgs/ManualInfo";
  }

  static const char* value(const ::graspit_msgs::ManualInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 axis\n\
int32 direction\n\
";
  }

  static const char* value(const ::graspit_msgs::ManualInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManualInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_msgs::ManualInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_msgs::ManualInfo_<ContainerAllocator>& v)
  {
    s << indent << "axis: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis);
    s << indent << "direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_MANUALINFO_H
