// Generated by gencpp from file graspit_msgs/TranslationInfo.msg
// DO NOT EDIT!


#ifndef GRASPIT_MSGS_MESSAGE_TRANSLATIONINFO_H
#define GRASPIT_MSGS_MESSAGE_TRANSLATIONINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_msgs
{
template <class ContainerAllocator>
struct TranslationInfo_
{
  typedef TranslationInfo_<ContainerAllocator> Type;

  TranslationInfo_()
    : axis()
    , direction()  {
    }
  TranslationInfo_(const ContainerAllocator& _alloc)
    : axis(_alloc)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _axis_type;
  _axis_type axis;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;




  typedef boost::shared_ptr< ::graspit_msgs::TranslationInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_msgs::TranslationInfo_<ContainerAllocator> const> ConstPtr;

}; // struct TranslationInfo_

typedef ::graspit_msgs::TranslationInfo_<std::allocator<void> > TranslationInfo;

typedef boost::shared_ptr< ::graspit_msgs::TranslationInfo > TranslationInfoPtr;
typedef boost::shared_ptr< ::graspit_msgs::TranslationInfo const> TranslationInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_msgs::TranslationInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace graspit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'graspit_msgs': ['/home/masatoshichang/robotics/fetch_ws/src/graspit_msgs/msg', '/home/masatoshichang/robotics/fetch_ws/devel/share/graspit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_msgs::TranslationInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_msgs::TranslationInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_msgs::TranslationInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29b03e24aa12fc30c591b02baf6c9d8f";
  }

  static const char* value(const ::graspit_msgs::TranslationInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29b03e24aa12fc30ULL;
  static const uint64_t static_value2 = 0xc591b02baf6c9d8fULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_msgs/TranslationInfo";
  }

  static const char* value(const ::graspit_msgs::TranslationInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string axis\n\
string direction\n\
";
  }

  static const char* value(const ::graspit_msgs::TranslationInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TranslationInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_msgs::TranslationInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_msgs::TranslationInfo_<ContainerAllocator>& v)
  {
    s << indent << "axis: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.axis);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_TRANSLATIONINFO_H
